export const faq = [
  {
    value: 'vizum',
    qCz: 'Potřebuje se na návštěvu Malediv vízum?',
    aCz: 'Ano, pokud plánujete zůstat déle než 30 dní. Je však vhodné kontaktovat místní úřady pro další informace ohledně případných omezení podle vaší státní příslušnosti.',
    qEn: 'Do I need a visa to visit the Maldives?',
    aEn: "Yes, if you plan to stay longer than 30 days. However, it's advisable to contact local authorities for further information on any restrictions that may apply to your nationality.",
    qRu: 'Нужна ли виза для посещения Мальдив?',
    aRu: 'Да, если вы планируете пребывать дольше 30 дней. Однако рекомендуется связаться с местными властями для получения дополнительной информации о возможных ограничениях, которые могут быть применимы к вашему гражданству.',
  },
  {
    value: 'cesta',
    qCz: 'Jak se dostat z letiště na ostrov Dhiffushi?',
    aCz: 'Transfer zařizujeme my, cesta trvá 45 minut rychlolodí',
    qEn: 'How can I get from the airport to Dhiffushi Island?',
    aEn: 'We arrange the transfer, the journey takes 45 minutes by speed boat',
    qRu: 'Как добраться с аэропорта на остров Диффуши?',
    aRu: 'Мы организуем трансфер, поездка займет 45 минут на быстроходном катере.',
  },
  {
    value: 'pocasi',
    qCz: 'Jaké je počasí na ostrově Dhiffushi?',
    aCz: 'Očekávejte průměrné denní teploty kolem 30 °C po celý rok.',
    qEn: 'What is the weather like on Dhiffushi Island?',
    aEn: 'Expect average daily temperatures around 30°C throughout the year.',
    qRu: 'Какая погода на острове Диффуши?',
    aRu: 'Ожидайте среднедневных температур около 30°C в течение всего года.',
  },
  {
    value: 'plaz',
    qCz: 'Jak vypadá pláž u penzionu?',
    aCz: 'Pláž je udržovaná v čistotě, máme zde vlastní lehátka a je zde malá hloubka.',
    qEn: 'What does the beach look like at the guesthouse?',
    aEn: 'The beach is kept clean, we have our own sunbeds and there is little depth.',
    qRu: 'Как выглядит пляж у гостевого дома?',
    aRu: 'Пляж чистый, у нас есть собственные шезлонги и небольшая глубина.',
  },
  {
    value: 'klimatizace',
    qCz: 'Jsou pokoje v penzionu Dhiffushi Inn vybaveny klimatizací?',
    aCz: 'Ano, všechny naše pokoje mají klimatizaci.',
    qEn: 'Are the rooms at Dhiffushi Inn air-conditioned?',
    aEn: 'Yes, all our rooms have air conditioning.',
    qRu: 'Есть ли кондиционеры в номерах гостиницы Dhiffushi Inn?',
    aRu: 'Да, все наши номера оснащены кондиционерами.',
  },
  {
    value: 'wifi',
    qCz: 'Je na ostrově dostupný internet?',
    aCz: 'Ano, máme vlastní WiFi síť pro naše hosty.',
    qEn: 'Is there internet access on the island?',
    aEn: 'Yes, we have our own WiFi network for our guests.',
    qRu: 'Есть ли доступ в интернет на острове?',
    aRu: 'Да, у нас есть собственная сеть WiFi для наших гостей.',
  },
  {
    value: 'ockovani',
    qCz: 'Potřebuji nějaké očkování pro pobyt?',
    aCz: 'Na Malediy není potřeba žádné očkování.',
    qEn: 'Do I need any vaccinations for my stay?',
    aEn: 'No vaccinations are required for the Maldives.',
    qRu: 'Нужны ли мне прививки для пребывания?',
    aRu: 'Для Мальдив не требуется никаких прививок.',
  },
  {
    value: 'mena',
    qCz: 'Jakou měnu mohu na ostrově použít?',
    aCz: 'Maledivské rufiyaa, americké dolary a eura.',
    qEn: 'What currency can I use there?',
    aEn: 'We accept Maldivian Rufiyaa, US dollars, and euros.',
    qRu: 'Какую валюту я могу использовать там?',
    aRu: 'Мы принимаем мальдивские руфии, доллары США и евро.',
  },
  {
    value: 'alkohol',
    qCz: 'Mohu si na ostrově koupit alkohol?',
    aCz: 'Ne. Prodej alkoholu na Maledivách je zakázán. Kousek od ostrova je ale loď, na které je možné alkohol pít.',
    qEn: 'Can I buy alcohol on the island?',
    aEn: 'No. The sale of alcohol is prohibited in the Maldives. But there is a boat just off the island where you can drink alcohol.',
    qRu: 'Могу ли я купить алкоголь на острове?',
    aRu: 'Нет. Продажа алкоголя на Мальдивах запрещена. Но недалеко от острова есть лодка, где можно выпить алкоголь.',
  },
  {
    value: 'obchod',
    qCz: 'Je na ostrově nějaký obchod?',
    aCz: 'Ano, je tu několik menších kráméčků, kde se dají koupit základní potraviny nebo kosmetika',
    qEn: 'Is there a shop on the island?',
    aEn: 'Yes, there are several small shops where you can buy basic food or cosmetics',
    qRu: 'Есть ли на острове магазин?',
    aRu: 'Да, здесь есть несколько небольших магазинов, где можно купить основные продукты или косметику.',
  },
  {
    value: 'platba',
    qCz: 'Jak zaplatím pobyt?',
    aCz: 'Hotově na místě v USD',
    qEn: 'How do I pay for my stay?',
    aEn: 'Cash on the spot in USD',
    qRu: 'Как оплатить проживание?',
    aRu: 'Наличные на месте в долларах США',
  },
  {
    value: 'deti',
    qCz: 'Jsou Maledivy vhodné pro děti?',
    aCz: 'Ano, díky pozvolné pláži a příjemnému klima určitě doporučujeme',
    qEn: 'Are the Maldives suitable for children?',
    aEn: 'Yes, thanks to the gently sloping beach and pleasant climate we definitely recommend it',
    qRu: 'Подходят ли Мальдивы для детей?',
    aRu: 'Да, благодаря пологому пляжу и приятному климату мы определенно рекомендуем это место.',
  },
  {
    value: 'bankomat',
    qCz: 'Je na ostrově bankomat?',
    aCz: 'Ano (vydává pouze místní měnu)',
    qEn: 'Is there an ATM on the island?',
    aEn: 'Yes (only issues local currency)',
    qRu: 'Есть ли на острове банкомат?',
    aRu: 'Да (выпускает только местную валюту)',
  },
  {
    value: 'jazyk',
    qCz: 'Co když neumím anglicky?',
    aCz: 'To není žádná překážka, vše s vámi vyřídíme v češtině a na ostrově máme českou delegátku, která vám bude k dispozici celou dobu',
    qEn: "What if I don't speak English?",
    aEn: 'This is no obstacle, everything will be arranged with you in Czech and we have a Czech delegate on the island who will be at your disposal all the time',
    qRu: 'Что делать, если я не говорю по-английски?',
    aRu: 'Это не помеха, все будет согласовано с вами на чешском языке, и у нас на острове есть чешский делегат, который будет в вашем распоряжении все время.',
  },
]
